-- This file has all schema updates as of 2016-10-27
-- This file is to be recreated annually so the <year>_Updates.sql will not get too long

/****** Object:  Database [CUSTOMRP_CURRENT]    Script Date: 10/20/2016 17:42:42 ******/
-- Assume database has been created already
/*
CREATE DATABASE [CUSTOMRP_CURRENT] ON  PRIMARY 
( NAME = N'CUSTOMRP', FILENAME = N'C:\SQLDataBase\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\CUSTOMRP_CURRENT.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CUSTOMRP_log', FILENAME = N'C:\SQLDataBase\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\CUSTOMRP_CURRENT_1.ldf' , SIZE = 1792KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CUSTOMRP_CURRENT] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QueryReport] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [QueryReport] SET ANSI_NULLS OFF
GO
ALTER DATABASE [QueryReport] SET ANSI_PADDING OFF
GO
ALTER DATABASE [QueryReport] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [QueryReport] SET ARITHABORT OFF
GO
ALTER DATABASE [QueryReport] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [QueryReport] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [QueryReport] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [QueryReport] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [QueryReport] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [QueryReport] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [QueryReport] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [QueryReport] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [QueryReport] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [QueryReport] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [QueryReport] SET  DISABLE_BROKER
GO
ALTER DATABASE [QueryReport] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [QueryReport] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [QueryReport] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [QueryReport] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [QueryReport] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [QueryReport] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [QueryReport] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [QueryReport] SET  READ_WRITE
GO
ALTER DATABASE [QueryReport] SET RECOVERY SIMPLE
GO
ALTER DATABASE [QueryReport] SET  MULTI_USER
GO
ALTER DATABASE [QueryReport] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [QueryReport] SET DB_CHAINING OFF
GO
*/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
DECLARE @currTime datetime
SET @currTime = GETDATE()

EXEC sp_executesql N'CREATE USER [qreport] FOR LOGIN [qreport] WITH DEFAULT_SCHEMA=[dbo]'

BEGIN -- [dbo].[USER]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[USER](
		[ID] [int] IDENTITY(1,1) NOT NULL,
		[UID] [nvarchar](200) NOT NULL,
		[GID] [int] NOT NULL,
		[DATABASEID] [int] NOT NULL,
		[PASSWORD] [nvarchar](50) NOT NULL,
		[VIEWLEVEL] [nvarchar](2000) NOT NULL,
		[REPORTGROUPLIST] [nvarchar](2000) NOT NULL,
		[USERGROUPLEVEL] [nvarchar](2000) NULL,
		[SETUPUSER] [int] NOT NULL,
		[REPORTRIGHT] [int] NOT NULL,
		[AUTODATE] [datetime] NOT NULL,
		[EMAIL] [nvarchar](2000) NULL,
		[USERGROUP] [nvarchar](100) NOT NULL,
		[NAME] [nvarchar](50) NULL,
		[SENSITIVITYLEVEL] [decimal](18, 2) NULL,
	 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
	 CONSTRAINT [IX_USER_1] UNIQUE NONCLUSTERED 
	(
		[UID] ASC,
		[GID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_USER_GID]  DEFAULT ((2)) FOR [GID]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_USER_APPLICATIONID]  DEFAULT ((1)) FOR [DATABASEID]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_USER_AUTODATE]  DEFAULT (getdate()) FOR [AUTODATE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[USER] ADD  CONSTRAINT [DF_USER_USERGROUP]  DEFAULT ('') FOR [USERGROUP]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_USERGROUP] FOREIGN KEY([GID])
	REFERENCES [dbo].[USERGROUP] ([ID])'
	EXEC sp_executesql N'ALTER TABLE [dbo].[USER] CHECK CONSTRAINT [FK_USER_USERGROUP]'

	SET IDENTITY_INSERT [dbo].[USER] ON
	INSERT [dbo].[USER] ([ID], [UID], [GID], [DATABASEID], [PASSWORD], [VIEWLEVEL], [REPORTGROUPLIST], [USERGROUPLEVEL], [SETUPUSER], [REPORTRIGHT], [AUTODATE], [EMAIL], [USERGROUP], [NAME], [SENSITIVITYLEVEL]) VALUES
		(1, N'admin', 1, 1, N'21232F297A57A5A743894A0E4A801FC3', N'1,2,3,4,5', N'1,3,4,5,6,7,14,15', N'1', 1, 15, @currTime, N'', N'2', N'Admin', CAST(16.50 AS Decimal(18, 2)))
	INSERT [dbo].[USER] ([ID], [UID], [GID], [DATABASEID], [PASSWORD], [VIEWLEVEL], [REPORTGROUPLIST], [USERGROUPLEVEL], [SETUPUSER], [REPORTRIGHT], [AUTODATE], [EMAIL], [USERGROUP], [NAME], [SENSITIVITYLEVEL]) VALUES
		(2, N'support', 1, 1, N'21232F297A57A5A743894A0E4A801FC3', N'1,2,3,4,5', N'1,3,4,5,6,7,14,15', N'1', 1, 15, @currTime, N'', N'2', N'Support', CAST(16.50 AS Decimal(18, 2)))
	SET IDENTITY_INSERT [dbo].[USER] OFF
	COMMIT
END

BEGIN -- [dbo].[APPLICATION]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[APPLICATION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESC] [nvarchar](max) NOT NULL,
	[CONFIG_VIEW1] [nvarchar](max) NOT NULL,
	[CONFIG_VIEW2] [nvarchar](max) NOT NULL,
	[CONFIG_VIEW3] [nvarchar](max) NOT NULL,
	[LASTMODIFYDATE] [datetime] NOT NULL,
	[LASTMODIFYUSER] [int] NOT NULL,
	[AUDODATE] [datetime] NOT NULL,
 CONSTRAINT [PK_APPLICATION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_APPLICATION] UNIQUE NONCLUSTERED 
(
	[NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[APPLICATION] ADD  CONSTRAINT [DF_APPLICATION_AUDODATE]  DEFAULT (getdate()) FOR [AUDODATE]'

	SET IDENTITY_INSERT [dbo].[APPLICATION] ON
	INSERT [dbo].[APPLICATION] ([ID], [NAME], [DESC], [CONFIG_VIEW1], [CONFIG_VIEW2], [CONFIG_VIEW3], [LASTMODIFYDATE], [LASTMODIFYUSER], [AUDODATE]) VALUES
		(1, N'DW-iHR', N'DW-iHR', N'1', N'2', N'3', @currTime, 1, @currTime)
	SET IDENTITY_INSERT [dbo].[APPLICATION] OFF
	COMMIT
END

BEGIN -- [dbo].[DATABASE]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[DATABASE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[APPLICATIONID] [int] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESC] [nvarchar](2000) NOT NULL,
	[STATUS] [int] NOT NULL,
	[LASTMODIFYDATE] [datetime] NOT NULL,
	[LASTMODIFYUSER] [int] NOT NULL,
	[AUDOTIME] [datetime] NOT NULL,
	[CONNECTIONSTRING] [nvarchar](2000) NOT NULL,
	[HASHKEY] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DATABASE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_DATABASE] UNIQUE NONCLUSTERED 
(
	[NAME] ASC,
	[APPLICATIONID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[DATABASE] ADD  CONSTRAINT [DF_DATABASE_LASTMODIFYDATE]  DEFAULT (getdate()) FOR [LASTMODIFYDATE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[DATABASE] ADD  CONSTRAINT [DF_DATABASE_AUDOTIME]  DEFAULT (getdate()) FOR [AUDOTIME]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[DATABASE] ADD  CONSTRAINT [DF_DATABASE_CONNECTIONSTRING]  ADD  DEFAULT ('') FOR [CONNECTIONSTRING]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[DATABASE]  WITH CHECK ADD  CONSTRAINT [FK_DATABASE_APPLICATION] FOREIGN KEY([APPLICATIONID])
	REFERENCES [dbo].[APPLICATION] ([ID])
	ON DELETE CASCADE'
	EXEC sp_executesql N'ALTER TABLE [dbo].[DATABASE] CHECK CONSTRAINT [FK_DATABASE_APPLICATION]'

	SET IDENTITY_INSERT [dbo].[DATABASE] ON
	INSERT [dbo].[DATABASE] ([ID], [APPLICATIONID], [NAME], [DESC], [STATUS], [LASTMODIFYDATE], [LASTMODIFYUSER], [AUDOTIME], [CONNECTIONSTRING], [HASHKEY]) VALUES
		(1, 1, N'DWHRMS_DEMO', N'DW-HR System', 1, @currTime, 1, @currTime, N'', N'com')
	INSERT [dbo].[DATABASE] ([ID], [APPLICATIONID], [NAME], [DESC], [STATUS], [LASTMODIFYDATE], [LASTMODIFYUSER], [AUDOTIME], [CONNECTIONSTRING], [HASHKEY]) VALUES
		(9999, 1, N'', N'Workaround to control SourceView display or not', 0, @currTime, 1, @currTime, N'', N'com')
	SET IDENTITY_INSERT [dbo].[DATABASE] OFF
	COMMIT
END

BEGIN -- [dbo].[SENSITIVITYLEVEL]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[SENSITIVITYLEVEL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATABASEID] [int] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[SLEVEL] [decimal](18, 2) NOT NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[AUDOTIME] [datetime] NOT NULL,
 CONSTRAINT [PK_SensitivityLevel] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_SENSITIVITYLEVEL] UNIQUE NONCLUSTERED 
(
	[SLEVEL] ASC,
	[DATABASEID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SENSITIVITYLEVEL] ADD  CONSTRAINT [DF_SensitivityLevel_AUDOTIME]  DEFAULT (getdate()) FOR [AUDOTIME]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SENSITIVITYLEVEL]  WITH CHECK ADD  CONSTRAINT [FK_SensitivityLevel_DATABASE] FOREIGN KEY([DATABASEID])
REFERENCES [dbo].[DATABASE] ([ID])'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SENSITIVITYLEVEL] CHECK CONSTRAINT [FK_SensitivityLevel_DATABASE]'
	EXEC sp_executesql N''
	EXEC sp_executesql N''
	EXEC sp_executesql N''


	SET IDENTITY_INSERT [dbo].[SENSITIVITYLEVEL] ON
	INSERT [dbo].[SENSITIVITYLEVEL] ([ID], [DATABASEID], [NAME], [SLEVEL], [DESCRIPTION], [AUDOTIME]) VALUES
		(1, 1, N'Top', CAST(16.50 AS Decimal(18, 2)), N'Top Level', @currTime)
	INSERT [dbo].[SENSITIVITYLEVEL] ([ID], [DATABASEID], [NAME], [SLEVEL], [DESCRIPTION], [AUDOTIME]) VALUES
		(2, 1, N'High', CAST(32.50 AS Decimal(18, 2)), N'High Level', @currTime)
	INSERT [dbo].[SENSITIVITYLEVEL] ([ID], [DATABASEID], [NAME], [SLEVEL], [DESCRIPTION], [AUDOTIME]) VALUES
		(3, 1, N'Normal', CAST(48.50 AS Decimal(18, 2)), N'Normal Level', @currTime)
	INSERT [dbo].[SENSITIVITYLEVEL] ([ID], [DATABASEID], [NAME], [SLEVEL], [DESCRIPTION], [AUDOTIME]) VALUES
		(4, 1, N'Low', CAST(64.50 AS Decimal(18, 2)), N'Low Level', @currTime)
	SET IDENTITY_INSERT [dbo].[SENSITIVITYLEVEL] OFF
	COMMIT
END

BEGIN -- [dbo].[USERGROUP]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[USERGROUP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATABASEID] [int] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](max) NOT NULL,
	[AUDODATE] [datetime] NOT NULL,
	[EXTEND] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_USERGROUP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[USERGROUP] ADD  CONSTRAINT [DF_USERGROUP_AUDODATE]  DEFAULT (getdate()) FOR [AUDODATE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[USERGROUP]  WITH CHECK ADD  CONSTRAINT [FK_USERGROUP_DATABASE] FOREIGN KEY([DATABASEID])
REFERENCES [dbo].[DATABASE] ([ID])
ON DELETE CASCADE'
	EXEC sp_executesql N'ALTER TABLE [dbo].[USERGROUP] CHECK CONSTRAINT [FK_USERGROUP_DATABASE]'
	EXEC sp_executesql N''
	
	SET IDENTITY_INSERT [dbo].[USERGROUP] ON
	INSERT [dbo].[USERGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDODATE], [EXTEND]) VALUES
		(1, 1, N'Admin Group', N'Administration Group', @currTime, N'')
	INSERT [dbo].[USERGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDODATE], [EXTEND]) VALUES
		(2, 1, N'Adv User', N'Administration Group', @currTime, N'')
	INSERT [dbo].[USERGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDODATE], [EXTEND]) VALUES
		(3, 1, N'User', N'Advance User', @currTime, N'')
	SET IDENTITY_INSERT [dbo].[USERGROUP] OFF
	COMMIT
END

BEGIN -- [dbo].[GROUPRIGHT]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[GROUPRIGHT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GID] [int] NOT NULL,
	[COMPANY] [nvarchar](50) NOT NULL,
	[REPORTGROUP] [nvarchar](50) NOT NULL,
	[CATEGARY] [nvarchar](50) NOT NULL,
	[SECURITY] [nvarchar](50) NOT NULL,
	[QUERY] [nvarchar](50) NOT NULL,
	[USERGROUP] [nvarchar](50) NOT NULL,
	[USERGROUPRIGHT] [nvarchar](50) NOT NULL,
	[USERSETUP] [nvarchar](50) NOT NULL,
	[AUDODATE] [datetime] NOT NULL,
	[EXTEND1] [nvarchar](50) NOT NULL,
	[EXTEND2] [nvarchar](50) NOT NULL,
	[EXTEND3] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_GROUPRIGHT_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_COMPANY]  DEFAULT ('') FOR [COMPANY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_REPORTGROUP]  DEFAULT ('') FOR [REPORTGROUP]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_CATEGARY]  DEFAULT ('') FOR [CATEGARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_QUERY]  DEFAULT ('') FOR [QUERY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_USERGROUP]  DEFAULT ('') FOR [USERGROUP]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_USERGROUPRIGHT]  DEFAULT ('') FOR [USERGROUPRIGHT]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_USERSETUP]  DEFAULT ('') FOR [USERSETUP]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_AUDODATE]  DEFAULT (getdate()) FOR [AUDODATE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_EXTEND1]  DEFAULT ('') FOR [EXTEND1]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_EXTEND2]  DEFAULT ('') FOR [EXTEND2]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] ADD  CONSTRAINT [DF_GROUPRIGHT_EXTEND3]  DEFAULT ('') FOR [EXTEND3]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT]  WITH CHECK ADD  CONSTRAINT [FK_GROUPRIGHT_USERGROUP] FOREIGN KEY([GID])
REFERENCES [dbo].[USERGROUP] ([ID])
ON DELETE CASCADE'
	EXEC sp_executesql N'ALTER TABLE [dbo].[GROUPRIGHT] CHECK CONSTRAINT [FK_GROUPRIGHT_USERGROUP]'
	EXEC sp_executesql N''
	EXEC sp_executesql N''
	EXEC sp_executesql N''

	SET IDENTITY_INSERT [dbo].[GROUPRIGHT] ON
	INSERT [dbo].[GROUPRIGHT] ([ID], [GID], [COMPANY], [REPORTGROUP], [CATEGARY], [SECURITY], [QUERY], [USERGROUP], [USERGROUPRIGHT], [USERSETUP], [AUDODATE], [EXTEND1], [EXTEND2], [EXTEND3]) VALUES
		(1, 2, N'Modify,View', N'Add,Modify,View', N'Modify', N'', N'Modify', N'Add,Modify,View', N'View', N'Add,Modify,View', @currTime, N'', N'', N'')
	INSERT [dbo].[GROUPRIGHT] ([ID], [GID], [COMPANY], [REPORTGROUP], [CATEGARY], [SECURITY], [QUERY], [USERGROUP], [USERGROUPRIGHT], [USERSETUP], [AUDODATE], [EXTEND1], [EXTEND2], [EXTEND3]) VALUES
		(2, 1, N'Add,Delete,Modify,View', N'Add,Delete,Modify,View', N'Add,Delete,Modify,View', N'Add,Delete,Modify,View', N'Add,Delete,Modify,View', N'Add,Delete,Modify,View', N'Add,Delete,Modify,View', N'Add,Delete,Modify,View', @currTime, N'Add,Delete,Modify,View', N'Add,Delete,Modify,View', N'')
	SET IDENTITY_INSERT [dbo].[GROUPRIGHT] OFF
	COMMIT
END

BEGIN -- [dbo].[RPCATEGORY]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[RPCATEGORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DATABASEID] [int] NOT NULL,
	[AUDODATE] [datetime] NOT NULL,
	[DESCRIPTION] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_RPCATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_RPCATEGORY] UNIQUE NONCLUSTERED 
(
	[NAME] ASC,
	[DATABASEID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[RPCATEGORY] ADD  CONSTRAINT [DF_RPCATEGORY_APPLICATIONID]  DEFAULT ((1)) FOR [DATABASEID]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[RPCATEGORY] ADD  CONSTRAINT [DF_RPCATEGORY_AUDODATE]  DEFAULT (getdate()) FOR [AUDODATE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[RPCATEGORY] ADD  CONSTRAINT [DF_RPCATEGORY_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[RPCATEGORY]  WITH CHECK ADD  CONSTRAINT [FK_RPCATEGORY_DATABASE] FOREIGN KEY([DATABASEID])
REFERENCES [dbo].[DATABASE] ([ID])'
	EXEC sp_executesql N'ALTER TABLE [dbo].[RPCATEGORY] CHECK CONSTRAINT [FK_RPCATEGORY_DATABASE]'
	
	SET IDENTITY_INSERT [dbo].[RPCATEGORY] ON
	INSERT [dbo].[RPCATEGORY] ([ID], [NAME], [DATABASEID], [AUDODATE], [DESCRIPTION]) VALUES
		(1, N'Daily', 1, @currTime, N'Daily')
	INSERT [dbo].[RPCATEGORY] ([ID], [NAME], [DATABASEID], [AUDODATE], [DESCRIPTION]) VALUES
		(2, N'Monthly', 1, @currTime, N'Monthly')
	INSERT [dbo].[RPCATEGORY] ([ID], [NAME], [DATABASEID], [AUDODATE], [DESCRIPTION]) VALUES
		(3, N'Yearly', 1, @currTime, N'Yearly')
	INSERT [dbo].[RPCATEGORY] ([ID], [NAME], [DATABASEID], [AUDODATE], [DESCRIPTION]) VALUES
		(4, N'General', 1, @currTime, N'General')
	SET IDENTITY_INSERT [dbo].[RPCATEGORY] OFF
	COMMIT
END

BEGIN -- [dbo].[REPORTGROUP]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[REPORTGROUP](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATABASEID] [int] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](max) NOT NULL,
	[AUDOTIME] [datetime] NOT NULL,
 CONSTRAINT [PK_REPORTGROUP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORTGROUP] ADD  CONSTRAINT [DF_REPORTGROUP_DADOTIME]  DEFAULT (getdate()) FOR [AUDOTIME]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORTGROUP]  WITH CHECK ADD  CONSTRAINT [FK_REPORTGROUP_DATABASE] FOREIGN KEY([DATABASEID])
REFERENCES [dbo].[DATABASE] ([ID])'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORTGROUP] CHECK CONSTRAINT [FK_REPORTGROUP_DATABASE]'
	
	SET IDENTITY_INSERT [dbo].[REPORTGROUP] ON
	INSERT [dbo].[REPORTGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDOTIME]) VALUES
		(1, 1, N'Payroll', N'Payroll report', @currTime)
	INSERT [dbo].[REPORTGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDOTIME]) VALUES
		(2, 1, N'Staff', N'Staff Report', @currTime)
	INSERT [dbo].[REPORTGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDOTIME]) VALUES
		(3, 1, N'MPF', N'MPF Report', @currTime)
	INSERT [dbo].[REPORTGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDOTIME]) VALUES
		(4, 1, N'Taxation', N'Taxation Report', @currTime)
	INSERT [dbo].[REPORTGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDOTIME]) VALUES
		(5, 1, N'Letter', N'Letter', @currTime)
	INSERT [dbo].[REPORTGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDOTIME]) VALUES
		(6, 1, N'Attendance', N'Attendance', @currTime)
	INSERT [dbo].[REPORTGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDOTIME]) VALUES
		(7, 1, N'SelfService', N'Self Service Portal', @currTime)
	INSERT [dbo].[REPORTGROUP] ([ID], [DATABASEID], [NAME], [DESCRIPTION], [AUDOTIME]) VALUES
		(8, 1, N'Office', N'Office', @currTime)
	SET IDENTITY_INSERT [dbo].[REPORTGROUP] OFF
	COMMIT
END

BEGIN -- [dbo].[AUDITLOG]

	EXEC sp_executesql N'CREATE TABLE [dbo].[AUDITLOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[MessageType] [int] NOT NULL,
	[ModuleName] [nvarchar](255) NOT NULL,
	[Message] [nvarchar](255) NOT NULL,
	[MessageDetail] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
	
END

BEGIN -- [dbo].[ERRORLOG]

	EXEC sp_executesql N'CREATE TABLE [dbo].[ERRORLOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[Message] [nvarchar](255) NOT NULL,
	[StackTrace] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
	
END

BEGIN -- [dbo].[SOURCEVIEW]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[SOURCEVIEW](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SOURCEVIEWNAME] [nvarchar](50) NOT NULL,
	[DATABASEID] [int] NOT NULL,
	[SOURCETYPE] [int] NOT NULL,
	[TBLVIEWNAME] [nvarchar](128) NOT NULL,
	[AUDODATE] [datetime] NOT NULL,
	[VIEWLEVEL] [decimal](18, 2) NOT NULL,
	[DESC] [nvarchar](50) NULL,
	[FORMATTYPE] [int] NULL,
 CONSTRAINT [PK_SOURCEVIEW] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SOURCEVIEW] ADD  CONSTRAINT [DF_SOURCEVIEW_APPLICATIONID]  DEFAULT ((1)) FOR [DATABASEID]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SOURCEVIEW] ADD  CONSTRAINT [DF_SOURCEVIEW_SOURCETYPE]  DEFAULT ((0)) FOR [SOURCETYPE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SOURCEVIEW] ADD  CONSTRAINT [DF_SOURCEVIEW_TBLVIEWNAME]  DEFAULT ('') FOR [TBLVIEWNAME]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SOURCEVIEW] ADD  CONSTRAINT [DF_SOURCEVIEW_AUTOTIME]  DEFAULT (getdate()) FOR [AUDODATE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SOURCEVIEW] ADD  CONSTRAINT [DF_SOURCEVIEW_VIEWLEVEL]  DEFAULT ((1)) FOR [VIEWLEVEL]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SOURCEVIEW] ADD  CONSTRAINT [DF_SOURCEVIEW_DESC]  DEFAULT ('') FOR [DESC]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SOURCEVIEW]  WITH CHECK ADD  CONSTRAINT [FK_SOURCEVIEW_SOURCEVIEW] FOREIGN KEY([DATABASEID])
REFERENCES [dbo].[DATABASE] ([ID])
ON DELETE CASCADE'
	EXEC sp_executesql N'ALTER TABLE [dbo].[SOURCEVIEW] CHECK CONSTRAINT [FK_SOURCEVIEW_SOURCEVIEW]'
	COMMIT
END

BEGIN -- [dbo].[SOURCEVIEWCOLUMN]

	EXEC sp_executesql N'CREATE TABLE [dbo].[SOURCEVIEWCOLUMN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SVID] [int] NOT NULL,
	[COLUMNNAME] [nvarchar](128) NOT NULL,
	[DISPLAYNAME] [nvarchar](128) NULL,
	[COLUMNTYPE] [int] NOT NULL,
	[COLUMNCOMMENT] [nvarchar](max) NOT NULL,
	[FORMULAFIELDID] [int] NULL,
	[HIDDEN] [bit] NOT NULL,
	[DEFAULTDISPLAYNAME] [nvarchar](128) NULL,
 CONSTRAINT [PK_SOURCEVIEWCOLUMN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'

END

BEGIN -- [dbo].[FORMULAFIELD]

	EXEC sp_executesql N'CREATE TABLE [dbo].[FORMULAFIELD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FIELDNAME] [nvarchar](128) NOT NULL,
	[SVID] [int] NOT NULL,
	[RPID] [int] NULL,
	[FUNCTION] [int] NOT NULL,
 CONSTRAINT [PK_FORMULAFIELD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]'

END

BEGIN -- [dbo].[FORMULAPARAM]

	EXEC sp_executesql N'CREATE TABLE [dbo].[FORMULAPARAM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SVID] [int] NOT NULL,
	[RPID] [int] NULL,
	[PARAMTYPE] [int] NOT NULL,
	[VALUE1] [nvarchar](max) NULL,
	[FORMULAFIELDID] [int] NULL,
 CONSTRAINT [PK_FORMULAPARAM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'

END
	
BEGIN -- [dbo].[REPORT]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[REPORT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATABASEID] [int] NOT NULL,
	[SVID] [int] NOT NULL,
	[REPORTNAME] [nvarchar](50) NOT NULL,
	[AUDODATE] [datetime] NOT NULL,
	[CATEGORY] [int] NOT NULL,
	[TYPE] [int] NOT NULL,
	[REPORTGROUPLIST] [int] NOT NULL,
	[RPTITLE] [nvarchar](50) NOT NULL,
	[ADDUSER] [int] NOT NULL,
	[DEFAULTFORMAT] [int] NOT NULL,
	[EXTENDFIELD] [nvarchar](2000) NOT NULL,
	[PRINT_ORIENTATION] [int] NOT NULL,
	[PRINT_FITTOPAGE] [smallint] NOT NULL,
	[REPORT_HEADER] [nvarchar](255) NOT NULL,
	[REPORT_FOOTER] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_REPORT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_REPORT] UNIQUE NONCLUSTERED 
(
	[REPORTNAME] ASC,
	[DATABASEID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_APPLICATION]  DEFAULT ((1)) FOR [DATABASEID]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_AUTOTIME]  DEFAULT (getdate()) FOR [AUDODATE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_CATEGORY]  DEFAULT ((1)) FOR [CATEGORY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_TYPE]  DEFAULT ((1)) FOR [TYPE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_DISTRIBUTION]  DEFAULT ((1)) FOR [REPORTGROUPLIST]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_RPTITLE]  DEFAULT ('') FOR [RPTITLE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_ADDUSER]  DEFAULT ((1)) FOR [ADDUSER]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_DEFAULTFORMAT]  DEFAULT ((1)) FOR [DEFAULTFORMAT]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_EXTENDFIELD]  DEFAULT ('') FOR [EXTENDFIELD]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_PRINT_ORIENTATION]  DEFAULT ((-1)) FOR [PRINT_ORIENTATION]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_PRINT_FITTOPAGE]  DEFAULT ((-1)) FOR [PRINT_FITTOPAGE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_REPORT_HEADER]  DEFAULT ('') FOR [REPORT_HEADER]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] ADD  CONSTRAINT [DF_REPORT_REPORT_FOOTER]  DEFAULT ('') FOR [REPORT_FOOTER]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT]  WITH CHECK ADD  CONSTRAINT [FK_REPORT_REPORT] FOREIGN KEY([SVID])
REFERENCES [dbo].[SOURCEVIEW] ([ID])
ON DELETE CASCADE'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORT] CHECK CONSTRAINT [FK_REPORT_REPORT]'
	COMMIT
END

BEGIN -- [dbo].[REPORTCOLUMN]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[REPORTCOLUMN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RPID] [int] NOT NULL,
	[COLUMNNAME] [nvarchar](max) NOT NULL,
	[COLUMNFUNC] [int] NOT NULL,
	[CRITERIA1] [nvarchar](max) NULL,
	[CRITERIA2] [nvarchar](max) NULL,
	[CRITERIA3] [nvarchar](max) NULL,
	[CRITERIA4] [nvarchar](max) NULL,
	[AUDODATE] [datetime] NULL,
	[SOURCEVIEWCOLUMNID] [int] NOT NULL,
	[DISPLAYNAME] [nvarchar](128) NULL,
	[COLUMNTYPE] [int] NOT NULL,
	[COLUMNCOMMENT] [nvarchar](max) NOT NULL,
	[FORMULAFIELDID] [int] NULL,
	[HIDDEN] [int] NOT NULL,
	[SEQ] [int] NULL,
	[EXCEL_COLWIDTH] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_REPORTCOLUMN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORTCOLUMN] ADD  CONSTRAINT [DF_SELECTEDCOLUMN_AUDODATE]  DEFAULT (getdate()) FOR [AUDODATE]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORTCOLUMN] ADD  CONSTRAINT [DF_REPORTCOLUMN_EXCEL_COLWIDTH]  DEFAULT ((-1)) FOR [EXCEL_COLWIDTH]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORTCOLUMN]  WITH CHECK ADD  CONSTRAINT [FK_SELECTEDCOLUMN_REPORT] FOREIGN KEY([RPID])
REFERENCES [dbo].[REPORT] ([ID])
ON DELETE CASCADE'
	EXEC sp_executesql N'ALTER TABLE [dbo].[REPORTCOLUMN] CHECK CONSTRAINT [FK_SELECTEDCOLUMN_REPORT]'
	COMMIT
END

BEGIN -- [dbo].[WORDTEMPLATE]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[WORDTEMPLATE](
	[WORDTEMPLATEID] [int] IDENTITY(1,1) NOT NULL,
	[WORDTEMPLATEName] [nvarchar](50) NULL,
	[Description] [nvarchar](200) NULL,
	[VIEWID] [int] NOT NULL,
	[TemplateFileName] [nvarchar](100) NOT NULL,
	[DataFileName] [nvarchar](100) NOT NULL,
	[ModifyDate] [datetime] NOT NULL,
	[ModifyUser] [int] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [int] NOT NULL
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_WORDTEMPLATE_VIEWID] ON [dbo].[WORDTEMPLATE] 
(
	[VIEWID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDTEMPLATE] ADD  CONSTRAINT [DF_WORDTEMPLATE_ModifyDate]  DEFAULT (getdate()) FOR [ModifyDate]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDTEMPLATE] ADD  CONSTRAINT [DF_WORDTEMPLATE_ModifyUser]  DEFAULT ((1)) FOR [ModifyUser]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDTEMPLATE] ADD  CONSTRAINT [DF_WORDTEMPLATE_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDTEMPLATE] ADD  CONSTRAINT [DF_WORDTEMPLATE_CreateUser]  DEFAULT ((1)) FOR [CreateUser]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDTEMPLATE]  WITH CHECK ADD  CONSTRAINT [FK_WORDTEMPLATE_SOURCEVIEW] FOREIGN KEY([VIEWID])
REFERENCES [dbo].[SOURCEVIEW] ([ID])
ON DELETE CASCADE'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDTEMPLATE] CHECK CONSTRAINT [FK_WORDTEMPLATE_SOURCEVIEW]'
	COMMIT
END

BEGIN -- [dbo].[WORDFILE]
	BEGIN TRAN
	EXEC sp_executesql N'CREATE TABLE [dbo].[WORDFILE](
	[WordFileID] [int] IDENTITY(1,1) NOT NULL,
	[WordFileName] [nvarchar](100) NOT NULL,
	[OrigFileName] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](200) NOT NULL,
	[WordTemplateID] [int] NOT NULL,
	[RPID] [int] NOT NULL,
	[ModifyDate] [datetime] NOT NULL,
	[ModifyUser] [int] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[CreateUser] [int] NOT NULL,
 CONSTRAINT [PK_WORDFILE] PRIMARY KEY CLUSTERED 
(
	[WordFileID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_WORDWILE_RPID] ON [dbo].[WORDFILE] 
(
	[RPID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
ON [PRIMARY]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDFILE] ADD  CONSTRAINT [DF_WORDFILE_ModifyDate]  DEFAULT (getdate()) FOR [ModifyDate]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDFILE] ADD  CONSTRAINT [DF_WORDFILE_ModifyUser]  DEFAULT ((1)) FOR [ModifyUser]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDFILE] ADD  CONSTRAINT [DF_WORDFILE_CreateDate]  DEFAULT (getdate()) FOR [CreateDate]'
	EXEC sp_executesql N'ALTER TABLE [dbo].[WORDFILE] ADD  CONSTRAINT [DF_WORDFILE_CreateUser]  DEFAULT ((1)) FOR [CreateUser]'
	COMMIT
END

BEGIN -- [dbo].[SYSTEMPARAMETER]
	BEGIN TRAN
		EXEC sp_executesql N'CREATE TABLE [dbo].[SYSTEMPARAMETER](
	[Name] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](200) NOT NULL,
	[Value] [nvarchar](100) NOT NULL,
	[Remark] [nvarchar](max) NULL,
 CONSTRAINT [PK_SYSTEMPARAMETER] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]'
		EXEC sp_executesql N'INSERT INTO [dbo].[SYSTEMPARAMETER] VALUES
		(N''SCHEMA_VERSION'', N''Database schema version'', N''2016-10-27'', N'''')'
	COMMIT
END